all: main.cpp classes.cpp classes.h vitals.cpp vitals.h fitness.cpp fitness.h bloodGlucose.cpp bloodGlucose.h
	g++ main.cpp classes.cpp vitals.cpp fitness.cpp bloodGlucose.cpp -o output
clean:
	rm -f output
